name: personal_expense_tracker
description: "A financial tracking app with dark theme"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  # UI
  cupertino_icons: ^1.0.8

  # Firebase
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  cloud_firestore: ^5.4.4

  # State Management
  provider: ^6.1.2

  # Charts
  fl_chart: ^0.69.0

  # PDF Export
  pdf: ^3.11.1
  printing: ^5.13.2
  path_provider: ^2.1.4

  # Formatting
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true